---
- name: Enable internet services
  hosts: centos1
  become: true
  tasks:
    - name: Install latest version of firewalld, httpd, mariadb-server, php and php-mysqlnd
      ansible.builtin.dnf:
        name:
          - firewalld
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
        state: latest
    
    - name: Enable and run firewall
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: firewalld permits http service
      ansible.posix.firewalld:
       service: http
       permanent: true
       state: enabled
       immediate: true

    - name: Enable and run httpd
      ansible.builtin.service:
       name: httpd
       state: started
       enabled: true

    - name: Enable and run mariadb-server
      ansible.builtin.service:
       name: mariadb
       state: started
       enabled: true

    - name: Copy file
      ansible.builtin.copy:
        src: /home/memehack/ansible-project/ansible/index.php
        dest: /var/www/html/
        mode: 0644

